<?php

/**
 * @package d-tester
 * @subpackage administration subsystem
 * @version 1.2 RC1
 * @name diagram constants
 * @author Yuriy Bezgachnyuk
 * @copyright 2005-2008 Yuriy Bezgachnyuk, IF, Ukraine
 * 
 * All rights reserved
 */
 
define("DIA_GROUPS_QUALITY", 0);

define("DIA_USERS_GROUP_QUALITY", 1);

define("DIA_USER_TEST_DETAILS", 2);

define("DIA_STAT_MATRIX_ALL_USERS", 3);

define("DIA_STAT_MATRIX_USER", 4);

define("DIA_STAT_MATRIX_NEW", 5);

?>