<?php

/**
 * @package d-tester
 * @subpackage administration subsystem [Export unit]
 * @version 1.2 RC1
 * @name export unit global constants
 * @author Yuriy Bezgachnyuk
 * @copyright 2005-2008 Yuriy Bezgachnyuk, IF, Ukraine
 * 
 * All rights reserved
 */

define("EX_dtXML_FORMAT", 0);

define("EX_MOODLEXML_FORMAT", 1);

define("EX_GIFT_FORMAT", 2);

define("EX_dtXMLv2_FORMAT", 4);

?>