<?php

/**
 * @package d-tester
 * @subpackage global [a/t]
 * @version 1.2 RC1
 * @name q_types global constants
 * @author Yuriy V. Bezgachnyuk
 * @copyright 2007-2008 Yuriy V. Bezgachnyuk
 *
 * Start date:  04/04/2007 
 * Last update: 08/01/2008 18:33 GMT +02:00 
 *
 * All Rights Reserved
 */

define("SIMPLE_CHOICE" ,0);

define("SIMPLE_CHOICE_IMG" ,1);

define("MULTI_CHOICE" ,2);

define("MULTI_CHOICE_IMG" ,3);

define("INPUT_FIELD" ,4);

define("INPUT_FIELD_IMG" ,5);

define("TASK_FORM", 6);

define("TASK_FORM_IMG", 7);

define("NUMERICAL" ,8);

define("NUMERICAL_IMG" ,9);

?>