<?php

/**
 * @package d-tester
 * @subpackage tester subsystem
 * @version 1.2 RC1
 * @name Ukrainian Language pack [codepage: cp1251]
 * @author Yuriy Bezgachnyuk
 * @copyright 2005-2012 Yuriy Bezgachnyuk, IF, Ukraine
 * 
 * Start date: 09/02/2005
 * Last update: 02/11/2011 09:10 GMT +02:00
 * 
 * All rights reserved
 */

//basic 
$lang['tester_title']="d-tester v. 1.2 Release Candidate 1 build: 19/06/2012";
$lang['select_subject']="<b>Вибір предмету</b>";
$lang['reg_subjects']="Зареєстровані предмети";

$lang['how_subjects']="Зареєстрованих предметів";

$lang['num']="№ п/п";
$lang['subj_name']="Назва предмету";
$lang['how_tests']="Кількість тестів";
$lang['status']="Статус";
$lang['enable']="<b><font color=\"Blue\">Доступно</font></b>";
$lang['disable']="<b><font color=\"Red\">Недоступно</font></b>";

// login
$lang['entry_capt']="<b>Вхід в систему</b>";
$lang['login_select_user']="Виберіть користувача...";
$lang['login_select_group']="Виберіть групу...";
$lang['user_name']="<b>Прізвище і ім&#180;я</b>";
$lang['group_name']="<b>Група</b>";
$lang['pass_word']="<b>Пароль</b>";
$lang['test_name']="<b>Тест</b>";
$lang['admin_name']="<b>Адміністратор</b>";
$lang['admin_quote']="<b>Пароль адміністратора</b>";
$lang['enter_button']="Вхід";
$lang['student']="<b>Студент</b>";
$lang['task']="<b><i>Завдання %s з %s</i></b>";
$lang['task_level']=" [<b><i>Рівень %s</i></b>]";
$lang['time_ream']="<i>Час на роздуми:</i>";
$lang['a_warning']="<font color=\"Red\">*</font>Якщо невибрати жодного варіанту результат відповіді буде 0";

// Nav
$lang['nav_q']="Перейти до завдання ";
$lang['man_end']="Завершити тестування";

// Results Sections
$lang['OK']="Підтвердити";
$lang['of']="з";
$lang['results_capt']="<b>Результат</b>";
$lang['result']="<b>Результат</b>";
$lang['res_status']="<b>Висновок</b>";
$lang['res_good']="<font color=\"blue\"><b>ТЕСТ ПРОЙДЕНО</b></font>";
$lang['res_bad']="<font color=\"red\"><b>ТЕСТ НЕ ПРОЙДЕНО</b></font>";
$lang['full_rating']="<b>Загальний результат</b>";
$lang['res_details']="<b>Детальніша інформація</b>";
$lang['res_quality']="<b>Якість знань</b>";
$lang['true_answers']="<b>Правильних відповідей</b>";

// Copyright Information
$lang['aut_copy']="<b><font color=\"blue\">Copyright&nbsp;&copy; 2005-2012 </font>
<a href=\"http://k-zone.if.ua\" title=\"http://k-zone.if.ua [Karpaty Zone]\"><font color=\"blue\">Yuriy V. Bezgachnyuk</font></b></a><br>
Cascade Style Sheets (CSS) &copy; 2003 <a href=\"http://www.invisionpower.com\" target=\"_blank\">IPS inc</a>";

?>