<?php

/**
 * @package d-tester
 * @subpackage admin subsystem
 * @version 1.2 RC1
 * @author Yuriy Bezgachnyuk
 * @copyright 2005-2012 Yuriy Bezgachnyuk, IF, Ukraine
 * @name language pack: Ukrainian, codepage: cp1251
 *
 * Start date: 04/04/2005
 * Last update: 02/11/2011 09:10 GMT +02:00
 *
 * All Rights Reserved
 */

$hlp_lang['main_title']="<font color=\"blue\"><b>Система дистанційної перевірки і оцінювання знань</b></font>";
$hlp_lang['tester_title']="<b><i>d-tester v. 1.2 Release Candidate 1 build: 19/06/2012</i></b>";
$hlp_lang['title']="Довідкова система d-tester";

$hlp_lang['doc_file']="help/d-tester_User_Manual_02_12_2007.pdf";

//themes
$hlp_lang['themes'][0]="<B>ПРО СИСТЕМУ...</B>";
$hlp_lang['themes'][1]="<B>Керівництво з експлуатації...</B>";

$hlp_lang['themes_m'][0]="Інформація про групу розробників системи";
$hlp_lang['themes_m'][1]="d_tester_User_Manual_02_12_2007.pdf";

?>