<?php

/**
 * @package d-tester
 * @subpackage admin subsystem
 * @version 1.2 RC1
 * @name Ukrainian Language pack [codepage: cp1251]
 * @author Yuriy Bezgachnyuk
 * @copyright 2005-2012 Yuriy Bezgachnyuk, IF, Ukraine
 * 
 * Start date: 09/02/2005
 * Last update: 02/11/2011 09:09 GMT +02:00
 * 
 * All rights reserved
 */

// System Information
$lang['system_version']="d-tester v. 1.2 Release Candidate 1 build: 19/06/2012";

// Login
$lang['login_act']="Адміністрування";
$lang['login_name']="<b>Ім&#180;я</b>";
$lang['login_pass']="<b>Пароль</b>";
$lang['login_submit']="Вхід";
$lang['logout_confirm']="Ви дійсно хочете завершити роботу з програмою?";
$lang['logout_warning']="<font color=\"blue\"><b>ДЛЯ ЗАВЕРШЕННЯ РОБОТИ З ПРОГРАМОЮ ОБОВ&#180;ЯЗКОВО НАТИСНІТЬ </b></font>";
$lang['login_error']= "Ім&#180;я користувача або пароль задані невірно";

// add hrefs 
$lang['add_new_group']="Додати нову групу";
$lang['add_new_user']="Додати нового студента";
$lang['add_new_subject']="Додати новий предмет";
$lang['add_new_test']="Додати новий тест";
$lang['add_new_task']="Додати нове завдання";
$lang['add_new_ip']="Додати нову адресу";
$lang['add_new_test_detail']="Додати новий параметр";
$lang['add_new_admin']="Додати нового адміністратора";
$lang['add_new_faculty']="Додати новий факультет";
$lang['add_new_spec']="Додати нову спеціальність";
$lang['generate_passwords']="Згенерувати паролі для всіх користувачів групи";

// buttons
$lang['tag_BR']="<br>";
$lang['apt_button']="Апостроф";
$lang['space_button']="SPACE";
$lang['reg_button']="Зареєструвати";
$lang['gen_pass_button']="Згенерувати пароль";
$lang['show_res_button']="Показати результат";
$lang['clear_button']="Очистити";
$lang['print_ver_button']="Версія для друку";
$lang['print_ver_button_up_10']="Форма УП-10 (Повна)";
$lang['next_button']="Далі...";

// managment hrefs
$lang['edit_href']="Редагувати";
$lang['del_button']="Видалити";
$lang['students_href']="Студенти";
$lang['tasks_href']="Завдання";

// main menu hrefs
$lang['menu_href']="Меню";
$lang['sys_stat_href']="Статистика системи";
$lang['groups_students_href']="Групи і студенти";
$lang['subjects_href']="Предмети";
$lang['tests_href']="Тести";
$lang['tests_href_for']="Тести предмету: ";
$lang['timetable_href']="Розклад";
$lang['timetable_href_for']="Розклад проведення тестування по предмету: ";
$lang['results_href']="Результати";
$lang['SQL_href']="SQL Manager";
$lang['HELP_href']="Допомога";
$lang['SESS_href']="Сеанси";
$lang['ORDERS_href']="Відомості";
$lang['IP_href']="IP Control";
$lang['logs']="Протоколи";
$lang['adm_logs_href']="Root Control";
$lang['admins_href']="Root Manager";
$lang['root_section']="Admin Service";
$lang['cptest_href']="Модуль копіювання";
$lang['export_href']="Модуль експорту";
$lang['import_href']="Модуль імпорту";
$lang['faculty_href']="Факультети";
$lang['specialities_href']="Спеціальності";
$lang['backup_href']="Резервна копія бази даних системи";
$lang['logout']="<font color=\"Red\"><b>ВИХІД</b></font>";

// main info
$lang['how_groups']="Зареєстрованих груп";
$lang['how_subjects']="Зареєстрованих предметів";
$lang['how_tests']="Зареєстрованих тестів";
$lang['how_users']="Зареєстрованих користувачів";
$lang['how_sessions']="Зареєстрованих сесій";
$lang['how_active_sess']="Активних сеансів";
$lang['how_logs']="Зареєстрованих входжень в систему";
$lang['how_questions']="Зареєстрованих завдань";
$lang['general_info']="Системна інформація";

// Forms
$lang['subj_name']="Назва предмету";
$lang['group_name']="Назва групи";
$lang['spec_name']="Спеціальність";
$lang['user_name']="Прізвище і ім&#180;я";
$lang['user_pass']="Пароль";
$lang['user_conf_pass']="Підтвердження пароля";
$lang['user_order_num']="№ інд. плану";
$lang['test_name']="Назва тесту";
$lang['test_how_tasks']="Завдань";
$lang['test_time']="Тривалість";
$lang['test_time_spec']="[ГГ:ХХ:СС]";
$lang['show_test_client']="Статус";
$lang['test_enable']="Доступно";
$lang['test_disable']="Недоступно";
$lang['test_subject']="Предмет";
$lang['test_details']="Деталі...";
$lang['how_chances']="Спроб:";
$lang['q_group']="<b>Рівень:</b> ";
$lang['sel_yes']="Так";
$lang['sel_no']="Ні";
$lang['faculty_name']="Факультет";

// tables captions
$lang['capt_test_details']="Додаткові параметри для тесту: ";
$lang['capt_manage']="Управління";
$lang['capt_num']="№ п/п";
$lang['capt_reg_num']="Реєстр. №";
$lang['capt_tasks']="Завдання тесту";
$lang['tasks_contains']="Містить %s завдан[-ь, -ня] необхідно %s";

// Logs
$lang['pages']="<b>Сторінка:</b>";
$lang['records']="<b>Записів:</b>";
$lang['capt_group']="Група ";
$lang['capt_student']="Студент";
$lang['capt_admin']="Адміністратор";
$lang['capt_time']="Час";
$lang['capt_enter']="Вхід";

// Logs -> Root Logs
$lang['capt_user_agent']="Програма";
$lang['capt_sess_id']="ID сеансу";

// Root -> Root Manager
$lang['adm_level_priv']="<b>Рівень доступу</b>";
$lang['capt_reg_admin']="Реєстрація нового адміністратора";
$lang['priv_href']="Привілеї";
$lang['priv_sch']="Схема привілеїв";
$lang['ROOT_PRIV']=array("SB_READ","SB_WRITE","SB_DELETE","RES_READ","RES_DELETE");

// Tasks
$lang['capt_media']=" [Тип завдання+(контейнер):";
$lang['capt_amedia']="Ресурс варіантів: ";
$lang['no_media']="Тільки текст";
$lang['image_media']="Зображення [jpeg, gif, png] + (Текст)";
$lang['show_pic']="Переглянути";

$lang['task_types']=array(
"Простий вибір [Radio Button]",
"Простий вибір [Radio Button] + зображеня [jpeg, gif, png]",
"Мульти-вибір [CheckBox]",
"Мульти-вибір [CheckBox] + зображеня [jpeg, gif, png]",
"Поле вводу",
"Поле вводу + зображеня [jpeg, gif, png]",
"Форма вводу (до 50000 символів)",
"Форма вводу (до 50000 символів) + зображеня [jpeg, gif, png]",
"Поле вводу з числовим аналізатором",
"Поле вводу з числовим аналізатором + зображеня [jpeg, gif, png]"
);

$lang['ans_num']="<b>Кількість варіантів: </b>";
$lang['ans_favorite']="<B>Варіант %s</B>";
$lang['capt_bool']="<B>Правильний варіант</B>";
$lang['capt_bool_f']="<b>Правильний</b>";
$lang['choose_file']="Виберіть файл...";
$lang['print_test']="Завантажити сторінку із друкованою версією всіх завдань даного тестового блоку";

$lang['IP_addr']="<B>IP Адреса</B>";
$lang['user_result']="<B>Інформація про результати оцінювання знань студента</B>";

// warning messages
$lang['apt_tip']="Для того, щоб додати у слово апостроф скористайтесь відповідною кнопкою";
$lang['grp_warning']="<FONT Color=\"Red\">*</FONT> При видаленні групи, буде також знищена інформація про всіх студентів даної групи";
$lang['test_warning']="<FONT Color=\"Red\">*</FONT> При видаленні тесту, буде також знищена інформація про всі завдання даного тесту";
$lang['task_warning']="<FONT Color=\"Red\">*</FONT> При видаленні завдання файли, які зв&#180;язані з ним не видаляються це можна зробити вручну або видалити весь тест";
$lang['ip_warning']="<FONT Color=\"Red\">*</FONT> При видаленні інформації про ІР адресу. З відповідного комп&acute;ютера не буде доступу до підсистеми адміністрування";
$lang['res_subj_tip']="<FONT color=\"Red\">*</FONT>Відображаються тільки ті предмети по яких студенти проходили тестування";
$lang['del_confirm']="Ви дійсно хочете видалити ";
$lang['gpass_confirm']="Паролі для користувачів даної групи будуть замінені на нові! Підтвердіть виконання операції";

// tables reg/edit caption
$lang['capt_reg_subj']="Реєстрація нового предмету";
$lang['capt_reg_timetable']="Реєстрація нового розкладу проведення тестування";
$lang['capt_reg_group']="Реєстрація нової групи";
$lang['capt_reg_user']="Реєстрація нового студента";
$lang['capt_reg_test']="Реєстрація нового тесту";
$lang['capt_reg_test_detail']="Реєстрація нових тестових параметрів";
$lang['capt_reg_task']="Реєстрація нового тестового завдання";
$lang['capt_reg_multimedia']="Реєстрація мультимедіа ресурсів тестового завдання";
$lang['capt_reg_ip']="Реєстрація нової ІР адреси";
$lang['capt_multi_res']="Мультимедіа ресурс";

// Results
$lang['capt_resume']="Звіт про проходження тестуваннь";
$lang['capt_resume_wizard']="Майстер створення звітів";
$lang['capt_res_det']="Детальна інформація про проходження тестування";
$lang['capt_test']="Тест";
$lang['capt_date']="Дата";
$lang['date_mask']="[РРРР-ММ-ДД]";

$lang['capt_mark']="Іспит";
$lang['capt_quality']="Якість";
$lang['capt_omark']="Рейтинг";
$lang['capt_ostatus'] = "Недопущений";
$lang['capt_full']="Підсумок";

$lang['capt_ID']="ID";
$lang['capt_common_res']="Загальний результат";
$lang['avg_test_result']="<B>Середній бал по групі</B>";
$lang['how_users_tested']="<B>Всього здали тест</B>";

$lang['capt_order']="Сортувати:";
$lang['capt_sort_order']="Вивід:";
$lang['capt_order_opt']="Додаткові параметри";
$lang['capt_some_attempts']="Декілька спроб:";
$lang['all_sess_res']="Всі результати";
$lang['user_avg_res']="Середній бал";
$lang['user_max_res']="Максимальний бал";
$lang['user_min_res']="Мінімальний бал";

$lang['res_choose_subject']="Вибір предмету";
$lang['res_details_href']="Деталі...";
$lang['res_group_warn']="<div align=\"center\" class=\"copyright\"><font color=red><b>При використанні функцій групування правильно відображаються лише імена користувачів і їх результат</b></font></div>";

// Results -> sort parameters
$lang['sort_date']="По даті";
$lang['sort_rate']="За рейтингом";
$lang['sort_user']="За користувачами";

$lang['lab_asc']="В порядку зростання";
$lang['lab_desc']="В порядку спадання";

// Results -> details
$lang['capt_name']="Параметр";
$lang['capt_value']="Значення";
$lang['capt_quests']="<b>Інформація про задані завдання</b>";
$lang['ans_id']="Відповідь";
$lang['true_ans']="<font color=\"blue\"><b>Правильна</b></font>";
$lang['false_ans']="<font color=\"red\"><b>Неправильна</b></font>";

// Results -> task information
$lang['capt_task_info']="Інформація про тестове завдання";
$lang['mmedia_res_type']="Тип питання:";

// Results -> diagram wizard
$lang['diagram_capt']="Майстер діаграм";
$lang['capt_dia_type']="Тип діаграми:";
$lang['dia_g_quality']="Результати здачі тесту по групам";
$lang['dia_ug_quality']="Результати здачі тесту студентами групи ";
$lang['dia_ut_quality']="Розподіл балів по рівнях";
$lang['avg_group_quality']="<B>Якість</B>";
$lang['avg_group_result']="<B>Рейтинг [СБ]</B>";
$lang['h_tasks_rate']="<B>Параметри<br>З/Б => (З*Б)</B>";
$lang['ut_total']="<B>Всього:</B>";

// Results --> details [Print version]
$lang['rpv_order']="Загальний звіт про проходження тестового контролю";
$lang['rpv_q_mark']="Оцінка за правильну відповідь";

// Results --> Stat Table
$lang['stable_wizard']="George Rasch Matrix";
$lang['EX_WINSTEP_FILE']="Експорт даних у форматі Winstep(Ministep)";
$lang['EX_CK_MOODLE_PLG_FILE'] = "EX_CK_MOODLE_PLG_FILE";

// Results --> new print version order
$lang['pro_form_type_name']="Форма УП-10";
$lang['pro_form_name']="ЕКЗАМЕНАЦІЙНА ВІДОМІСТЬ №____ від";
$lang['pro_univer_name']="Івано-Франківський національний технічний університет нафти і газу";
$lang['pro_faculty_name']="Факультет";
$lang['pro_spec_title']="Напрям підготовки (спеціальність)";
$lang['pro_course_name']="Курс";
$lang['pro_discipline_name']="Дисципліна:";
$lang['pro_disp_control_type'] = "Вид контролю";
$lang['pro_group_name']="Група:";
$lang['pro_teacher_name']="Викладачі (П.І.Б.):";
$lang['pro_teacher_lector']="лектора";
$lang['pro_teacher_lab']="які проводили пр., сем., лаб. заняття";

$lang['pro_exam_teacher_name']="Екзаменатор";
$lang['pro_responsible_person_name']="Відповідальний викладач";
$lang['pro_decan_name']="Декан факультету";

$lang['pro_std_year']="Навчальний рік";
$lang['pro_semestr']="Семестр";
$lang['pro_date']="Дата проведення екзамену";

$lang['pro_footer_all']="<b>Всього:</b>";
$lang['pro_from_pe']="з них:";
$lang['pro_footer_excelence']="відмінно";
$lang['pro_footer_good']="добре";
$lang['pro_footer_nbad']="задовільно";
$lang['pro_footer_bad']="незадовільно";

// s_markes
$lang['pro_footer_cannot_pass']="недоп.";
$lang['pro_footer_not_present']="неявок";
$lang['pro_footer_rate']="зарах.";
$lang['pro_footer_not_rate']="незарах.";

// results
$lang['pro_results_num']="№";
$lang['pro_results_ob_num']="№ індивідуального плану студента (залікової книжки)";
$lang['pro_results_PIB']="Прізвище, ім&acute;я, по-батькові";
$lang['pro_results_test_mark']="Екзаменаційна оцінка, бали";
$lang['pro_results_current_mark']="Підсумкова оцінка за модулями, бали";
$lang['pro_results_semestr_mark']="Семестрова оцінка за шкалою";
$lang['pro_results_100_balls_scale']="100-<br>бальною";
$lang['pro_results_ECTS_scale']="ECTS";
$lang['pro_results_4_balls_scale']="державною";
$lang['pro_results_teacher_sign']="Підпис екзаменатора";

// Test details
$lang['level_id']="Номер рівня";
$lang['tasks_num']="Кількість завдань";
$lang['level_rate']="Кількість балів";
$lang['test_parametr']="Параметр";
$lang['test_parametr_value']="Значення";
$lang['test_rate']="<b>Загальна кількість балів за тест:<b> ";
$lang['test_tasks']="<b>Необхідна кількість завдань:<b> ";

// Test types section
$lang['test_type']="Тип";
$lang['test_types']=array("Загальний", "Іспит/Залік", "Колоквіум", "Проміжний");


// Orders section
$lang['orders_title']="Відомості";

// SQL Manager
$lang['sql_man']="Управління базою даних системи";
$lang['manual_q']="<B>Формування запиту вручну</B>";
$lang['sql_tip']="тільки для досвідчених користувачів";
$lang['q_button']="Виконати запит";
$lang['r_button']="Очистити";
$lang['table']="<B>Таблиця:</B>";
$lang['add_to_query']="Додати у запит";
$lang['query_results']="Результати виконання запиту";

// Copy Form
$lang['cpform_title']="Модуль копіювання тестових завдань";
$lang['cpform_FROM']="Звідки:";
$lang['cpform_TO']="Куди:";
$lang['cpform_conf']="Чи ви дійсно хочете скопіювати завдання";

// Export Form
$lang['exform_title']="Модуль експорту тестових завдань";
$lang['exform_conf']="Підтвердіть виконаня операції експорту";
$lang['exform_format']="Формат:";
$lang['ex_formats']=array("d-tester XML [dt-XML]", "Moodle XML Format [Moodle XML]", "GIFT Format", "NAFTA TXT FORMAT", "d-tester XML v2 [for dtapi v. 2.1]");

// Import Form
$lang['imform_title']="Модуль імпорту тестових завдань";
$lang['imform_conf']="Підтвердіть виконаня операції імпорту";
$lang['imform_format']="Формат:";
$lang['imform_file']="Файл:";
$lang['im_formats']=array("d-tester XML [dt-XML]");
$lang['imform_level_offset']="Зміщення рівня завдань [+]";

// File upload unit messages
$lang['file_problem']="<b><font color=\"#FF0000\">[ПРОБЛЕМА]</font></b> ";
$lang['no_file_uploaded']="Файл не завантажено";
$lang['file_partialy_uploaded']="Файл завантажено лише частково";
$lang['file_upload_max_size']="Розмір файлу більший за максимально допустимий";
$lang['file_ini_max_size']="Розмір більший ніж заданий у параметрах сервера";
$lang['file_type_error']="Непідтримуваний формат файлу";

// footer
$lang['print_footer']="Звіт згенерований засобами автоматизованої системи дистанційної перевірки і оцінювання знань<br>";
$lang['print_footer'].="<b>".$lang['system_version']."</b>";

// Copyright Information
$lang['aut_copy']="<b><font color=\"blue\">Copyright&nbsp;&copy; 2005-2013 </font>
<a href=\"http://k-zone.if.ua\" title=\"http://k-zone.if.ua [Karpaty Zone]\"><font color=\"blue\">Yuriy V. Bezgachnyuk</font></a></b>
<br>Cascade Style Sheets (CSS) &copy; 2003 <a href=\"http://www.invisionpower.com\" target=\"_blank\">IPS inc</a>";

$lang['logo_copy']="<a href=\"http://k-zone.if.ua\" title=\"http://k-zone.if.ua [Karpaty Zone]\"><b>d-tester logo design by Yaroslav Bezgachnyuk</b></a>";
$lang['form_copy']="<a href=\"http://k-zone.if.ua\" title=\"http://k-zone.if.ua [Karpaty Zone]\"><b>admin login form design by Yuriy Lytvynenko</b></a>";
?>